user_list = [
  [ "germany@gmail.com", "germany", "germany" ],
  [ "france@gmail.com", "france", "france" ],
  [ "belgium@gmail.com", "belgium", "belgium" ],
  [ "netherlands@gmail.com", "netherlands", "netherlands" ]
]
user_list.each do |email, password, password_confirmation|
  User.create( email: email, password: password, password_confirmation: password_confirmation )
end
podcast_list = [
  [ "JavaScript Jabber", "Devchat.tv has a mission to empower programmers to change the world by helping them better understand the technologies, tools, processes, and possibilities of their craft.", "https://devchat.tv/js-jabber/" ],
  [ "Hardcore History", "History revisited", "https://www.dancarlin.com/hardcore-history-series/" ],
  [ "The Mission Daily by The Mission", "The Mission Daily is a podcast dedicated to accelerated learning and helping you become healthier, wealthier, and wiser.", "mission.org" ],
  [ "The Story by The Mission", "In The Mission’s podcast, The Story, you’ll discover the unknown backstories of trailblazers who changed the world!", "mission.org" ],
  [ "Tori Talk w/ Catori Langley Podcast", "I am Washingtonian through and through. I love my city and want to share with all of you exactly why that is.", "https://toritalkwebseries.com/tori-talk-web-show/" ],
  [ "The RE-Cast", "The Reboot, Revival, Rehash Cast (often shortened to the RE-Cast) is a weekly entertainment podcast hosted by PIEGUYRULZ and MonstersReview.", "http://www.digitalpodcast.com/feeds/go?feed_id=92014" ],
  [ "Kondo Comrades", "A podcast about the Life Changing Magic of Tidying Up!", "https://soundcloud.com/user-56605011" ],
  [ "Decipher Security Podcast", "The editors of Decipher talk with a rotating cast of security practitioners, researchers, and executives about a variety of topics in the security and privacy fields.", "https://duo.com/decipher/" ],
  [ "Modern Figures Podcast", "The Institute for African-American Mentoring in Computing Sciences (iAAMCS)", "http://modernfigurespodcast.com/" ],
  [ "Hinkle Heat Check", "Dive into all things Butler basketball with Lukas Harkins (BustingBrackets.com) and Jared Grubbs (ButlerHoops.com).", "https://hinkleheatcheck.podbean.com/" ],
  [ "PWTorch Dailycast", "PWTorch Dailycast features a line-up of seven weekly shows, with a new episode on each day of the week with a different focus. ", "https://www.spreaker.com/show/pwtorch" ],
  [ "The Naked Truth with Nicole Dei", "Join Nicole Dei for her bi-weekly podcast covering all things body positivity.", "https://anchor.fm/nicole-dei" ],
  [ "Nouf Hakeem", " Self-recovery • homemaking • lifestyle • humanism • storytelling ", "https://noufhakeem.com/" ],
  [ "MadHatterCast", "Matt and Dave heckle about theological errors relating to conspiracy and supernatural topics with a whole lot of gold in between.", "https://anchor.fm/madhattercast" ]
]
podcast_list.each do |title, description, url|
  Podcast.create( title: title, description: description, url: url )
end
review_list = [
  [ 1, "my ears hurt", 2, 3, 4, 1, 1 ],
  [ 2, "bad", 2, 3, 4, 2, 1 ],
  [ 3, "not worth it", 2, 3, 4, 3, 1 ],
  [ 4, "good", 2, 3, 4, 4, 1 ],
  [ 5, "bad", 2, 3, 4, 5, 1 ],
  [ 1, "good", 2, 3, 4, 6, 1 ],
  [ 2, "lousey", 2, 3, 4, 7, 1 ],
  [ 3, "bad", 2, 3, 4, 8, 1 ],
  [ 4, "good", 2, 3, 4, 9, 1 ],
  [ 5, "Didnt like the speaker but great content!", 2, 3, 4, 10, 1 ],
  [ 1, "bad", 2, 3, 4, 11, 1 ],
  [ 2, "good", 5, 4, 4, 12, 1 ],
  [ 3, "", 2, 3, 4, 13, 1 ],
  [ 4, "bad", 2, 3, 4, 14, 1 ],
  [ 5, "good", 5, 5, 4, 1, 2 ],
  [ 1, "lousey", 2, 3, 4, 2, 2 ],
  [ 2, "would definitely reccomend", 2, 1, 4, 3, 2 ],
  [ 3, "cool content, so so delivery", 2, 3, 4, 4, 2 ],
  [ 4, "good", 2, 2, 4, 5, 2 ],
  [ 5, "Was super educational", 2, 3, 4, 6, 2 ],
  [ 1, "good", 5, 3, 4, 7, 2 ],
  [ 2, "lousey", 2, 3, 4, 8, 2 ],
  [ 3, "wonderful", 2, 3, 1, 9, 2 ],
  [ 4, "good", 4, 3, 4, 10, 2 ],
  [ 5, "great listen!", 2, 3, 4, 11, 2 ],
  [ 1, "bad", 2, 3, 4, 12, 2 ],
  [ 2, "boring", 3, 4, 4, 13, 2 ],
  [ 3, "lousey", 2, 3, 1, 14, 2 ],
  [ 4, "bad", 2, 3, 4, 1, 3 ],
  [ 5, "handles like a dream", 5, 5, 4, 2, 3 ],
  [ 1, "would not reccomend", 2, 3, 4, 3, 3 ],
  [ 2, "bad", 2, 3, 4, 4, 3 ],
  [ 3, "good", 5, 2, 4, 5, 3 ],
  [ 4, "lousey", 2, 3, 1, 6, 3 ],
  [ 5, "bad", 2, 3, 4, 7, 3 ],
  [ 1, "good", 5, 2, 4, 8, 3 ],
  [ 2, "was not into the host", 2, 3, 4, 9, 3 ],
  [ 3, "bad", 2, 3, 4, 10, 3 ],
  [ 4, "good", 4, 1, 1, 11, 3 ],
  [ 5, "genius", 3, 3, 4, 12, 3 ],
  [ 1, "bad", 2, 3, 4, 13, 3 ],
  [ 2, "good", 3, 1, 4, 14, 3 ],
  [ 3, "best way to pass time on the train", 2, 1, 4, 1, 4 ],
  [ 4, "bad", 2, 3, 4, 2, 4 ],
  [ 5, "good", 3, 2, 4, 3, 4 ],
  [ 1, "lousey", 2, 3, 4, 4, 4 ],
  [ 2, "lame", 3, 3, 4, 5, 4 ],
  [ 3, "good", 2, 4, 4, 6, 4 ],
  [ 4, "the best", 2, 1, 4, 7, 4 ],
  [ 5, "bad", 3, 3, 4, 8, 4 ],
  [ 1, "good", 2, 5, 4, 9, 4 ],
  [ 2, "couldnt be less impressed", 2, 3, 4, 10, 4 ],
  [ 3, "bad", 3, 3, 4, 11, 4 ],
  [ 4, "good", 2, 5, 4, 12, 4 ],
  [ 5, "lousey", 2, 3, 4, 13, 4 ],
  [ 1, "bad", 3, 1, 4, 14, 4 ]
]
review_list.each do |rating, comment, binge_val, educational_val, entertainment_val, podcast_id, user_id|
  Review.create( rating: rating, comment: comment, binge_val: binge_val, educational_val: educational_val, entertainment_val: entertainment_val, podcast_id: podcast_id, user_id: user_id )
end
creator_list = [
   "Todd Bronco",
   "Artemis Steer",
   "Bruce Mang",
   "Remington Fox",
   "Gabi Gomez",
   "Will Clinton",
   "Dan Carlin",
   "Malcom Gladware",
   "Bill Williams"
]
creator_list.each do |name|
  Creator.create( name: name)
end
podcast_creatorship_list = [
  [ 1, 5],
  [ 2, 4],
  [ 3, 3],
  [ 4, 2],
  [ 5, 1],
  [ 6, 9],
  [ 7, 8],
  [ 8, 7],
  [ 9, 6],
  [ 10, 5],
  [ 11, 4],
  [ 12, 3],
  [ 13, 2],
  [ 14, 1],
  [ 1, 2],
  [ 2, 3],
  [ 3, 4],
  [ 4, 5],
  [ 5, 6],
  [ 6, 7],
  [ 7, 9]
 ]
podcast_creatorship_list.each do |podcast_id, creator_id|
  PodcastCreatorship.create( podcast_id: podcast_id, creator_id: creator_id)
end
vote_list = [
  [ 1, 1, 1],
  [ 1, 2, 1],
  [ 1, 3, 1],
  [ 1, 4, 1]
  [ 0, 2, 2],
  [ -1, 3, 3],
  [ 1, 4, 4],
  [ 1, 1, 5],
  [ 0, 2, 6],
  [ -1, 3, 7],
  [ 1, 4, 8],
  [ 1, 1, 9],
  [ 0, 2, 10],
  [ -1, 3, 11],
  [ 1, 4, 12],
  [ 1, 1, 13],
  [ 0, 2, 14],
  [ -1, 3, 15],
  [ 1, 4, 16],
  [ 1, 1, 17],
  [ 0, 2, 18],
  [ -1, 3, 19],
  [ 1, 4, 20],
  [ 1, 1, 21],
  [ 0, 2, 22],
  [ -1, 3, 23],
  [ 1, 4, 24],
  [ 1, 1, 25],
  [ 0, 2, 26],
  [ -1, 3, 27],
  [ 1, 4, 28],
  [ 1, 1, 29],
  [ 0, 2, 30],
  [ -1, 3, 31],
  [ 1, 4, 32],
  [ 1, 1, 33],
  [ 0, 2, 34],
  [ -1, 3, 35],
  [ 1, 4, 36],
  [ 1, 1, 37],
  [ 0, 2, 38],
  [ -1, 3, 39],
  [ 1, 4, 40],
  [ 1, 1, 41],
  [ 0, 2, 42],
  [ -1, 3, 43],
  [ 1, 4, 44],
  [ 1, 1, 45],
  [ 0, 2, 46],
  [ -1, 3, 47],
  [ 1, 4, 48],
  [ 1, 1, 49],
  [ 0, 2, 50],
  [ -1, 3, 51],
  [ 1, 4, 52],
  [ 1, 1, 53],
  [ 0, 2, 54],
  [ -1, 3, 55],
  [ 1, 4, 56]
]
vote_list.each do |value, user_id, review_id|
  Vote.create( value: value, user_id: user_id, review_id: review_id)
end
